name: CD

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  base_image_build:
    name: Base image build
    uses: ./.github/workflows/base-image-build.yml
    if: ${{ github.event_name != 'push' || github.event.pull_request.head.sha != github.sha }}
    secrets: inherit
  final_image_build:
    name: UpdateService image build
    uses: ./.github/workflows/final-image-build.yml
    needs: [base_image_build]
    if: ${{ github.event_name != 'push' || github.event.pull_request.head.sha != github.sha }}
    secrets: inherit
  unit_tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yml
    needs: [base_image_build]
    if: ${{ github.event_name != 'push' || github.event.pull_request.head.sha != github.sha }}
    secrets: inherit
  integration_tests:
    name: Integration Tests
    uses: ./.github/workflows/integration-tests.yml
    needs: [base_image_build]
    if: ${{ github.event_name != 'push' || github.event.pull_request.head.sha != github.sha }}
    secrets: inherit
  deploy_production:
    name: Deploy production
    needs: [base_image_build, final_image_build, unit_tests, integration_tests]
    environment: 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses: Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.LIVE_DEPLOY_HOST }}
          user: ${{ secrets.LIVE_DEPLOY_USER }}
          key: ${{ secrets.LIVE_DEPLOY_KEY }}
          known-hosts: ${{ secrets.LIVE_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: update-service
