name: Deploy Production

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.GITHUBWORKFLOWS_USER }}
          password: ${{ secrets.GITHUBWORKFLOWS_USER_PASSWORD }}
          port: ${{ secrets.DOCKER_HOST_PORT }}
          script: ./scripts/UpdateService/update_production.sh ${{ github.sha }}